[package]
name = "async-encrypted-stream"
version = "0.2.1"
authors = ["Ilson Roberto Balliego Junior <ilson.balliego@gmail.com>"]
edition = "2024"
description = "Async Read and Write wrappers around the chacha20 encryption primitives"
repository = "https://github.com/balliegojr/async-encrypted-stream"
license = "MIT"
keywords = ["aead", "chacha20", "poly1035", "tokio", "stream"]
categories = ["cryptography", "network-programming"]

[dependencies]
aead-stream = { version = "0.6", features = ["alloc"] }
bytes = "1.0"
chacha20poly1305 = "0.11"
pin-project-lite = "0.2"
tokio = { version = "1.23" }

[dev-dependencies]
pbkdf2 = "0.13"
sha2 = "0.11"
tokio = { version = "1.23.0", features = ["full"] }
